#!/bin/bash

# Это позволяет найти объекты, которые сценарий предварительного слияния убрал с пути,
# чтобы избежать конфликтов при запуске git clone, и переместить их на прежние места.
# В результате репозиторий git будет проверен, а сохранившиеся объекты окажутся
# в рабочем каталоге. Теперь Git воспринимает их как неотредактированные изменения
# в рабочей ветке, и вы можете добавить их или отменить.

# find ./ -name '*.vcsh-unclobber' -execdir rename -f '.vcsh-unclobber' '' {} \;
find ./ -name '*.vcsh-unclobber' -execdir rename -f -d 's/\.vcsh-unclobber//' {} \;

# while IFS= read -r line; do
#   files+=("$line")
# done < <(find ./ -name "*.vcsh-unclobber" -print0 | xargs -r -0)

# for f in $(find ./ -name "*.vcsh-unclobber" -print0 | xargs -r -0 realpath -q); do
# 	new=${f%.*}
# 	old=$f
# 	rm -f "$new" && mv "$old" "$new"
# done
